### ISSUE TITLE
Recommendations break if the ARN is a user (instead of a role)

### ISSUE THREAD

**Issue by jaydhulia** [common-fate/iamzero#13]
Hi, I was playing around with iamzero (really cool btw, love the work) when I noticed that recommendations wasn't working for me. I was using the `iamzero-python-example` and the provided guide and it still wasn't working. Then I noticed that the correct information was being transmitted to `iamzero` from the Python library, but it was erroring on the Go side. 
Specifically, in `pkg/recommendations/arn.go` there is a check for regex and it matches with a role but not a user.
The error:
```
... "msg":"web handler error","err":"could not find role in ARN arn:aws:iam::REDACTED:user/USERNAME" ...
```
I worked on an initial fix for this, but not sure if that's the approach you want to take!

**Comment by chrnorm** [comment]
I'll close this as #14 is merged which fixes the issue. In future though I'm keen for us to include some sort of testing for both IAM users and roles (your changes to the unit tests are great too though). Thanks @jaydhulia!
